export const cidadesPI = [
  { id: 1, nome: 'Amarante' },
  { id: 2, nome: 'Altos' },
  { id: 3, nome: 'Aroazes' },
  { id: 4, nome: 'Aroeiras do Itaim' },
  { id: 5, nome: 'Arraial' },
  { id: 6, nome: 'Assunção do Piauí' },
  { id: 7, nome: 'Água Branca' },
  { id: 8, nome: 'Água Doce do Norte' },
  { id: 9, nome: 'Água Mineral' },
  { id: 10, nome: 'Barras' },
  { id: 11, nome: 'Batalha' },
  { id: 12, nome: 'Bela Vista do Piauí' },
  { id: 13, nome: 'Belém do Piauí' },
  { id: 14, nome: 'Beneditinos' },
  { id: 15, nome: 'Bertolínia' },
  { id: 16, nome: 'Betânia do Piauí' },
  { id: 17, nome: 'Boa Hora' },
  { id: 18, nome: 'Bocaina' },
  { id: 19, nome: 'Bom Jesus' },
  { id: 20, nome: 'Bom Princípio do Piauí' },
  { id: 21, nome: 'Bonfim do Piauí' },
  { id: 22, nome: 'Boqueirão do Piauí' },
  { id: 23, nome: 'Brasileira' },
  { id: 24, nome: 'Brejo do Piauí' },
  { id: 25, nome: 'Buriti dos Lopes' },
  { id: 26, nome: 'Buriti dos Montes' },
  { id: 27, nome: 'Campo Alegre do Fidalgo' },
  { id: 28, nome: 'Campo Grande do Piauí' },
  { id: 29, nome: 'Campo Largo do Piauí' },
  { id: 30, nome: 'Campo Maior' },
  { id: 31, nome: 'Canavieira' },
  { id: 32, nome: 'Canto do Buriti' },
  { id: 33, nome: 'Capitão de Campos' },
  { id: 34, nome: 'Capitão Gervásio Oliveira' },
  { id: 35, nome: 'Caracol' },
  { id: 36, nome: 'Caraúbas do Piauí' },
  { id: 37, nome: 'Caridade do Piauí' },
  { id: 38, nome: 'Castelo do Piauí' },
  { id: 39, nome: 'Caxingó' },
  { id: 40, nome: 'Cocal' },
  { id: 41, nome: 'Cocal de Telha' },
  { id: 42, nome: 'Cocal dos Alves' },
  { id: 43, nome: 'Coivaras' },
  { id: 44, nome: 'Colônia do Gurguéia' },
  { id: 45, nome: 'Colônia do Piauí' },
  { id: 46, nome: 'Conceição do Canindé' },
  { id: 47, nome: 'Coronel José Dias' },
  { id: 48, nome: 'Corrente' },
  { id: 49, nome: 'Cristalândia do Piauí' },
  { id: 50, nome: 'Cristino Castro' },
  { id: 51, nome: 'Curimatá' },
  { id: 52, nome: 'Currais' },
  { id: 53, nome: 'Curralinhos' },
  { id: 54, nome: 'Curral Novo do Piauí' },
  { id: 55, nome: 'Demerval Lobão' },
  { id: 56, nome: 'Dirceu Arcoverde' },
  { id: 57, nome: 'Dom Expedito Lopes' },
  { id: 58, nome: 'Dom Inocêncio' },
  { id: 59, nome: 'Domingos Mourão' },
  { id: 60, nome: 'Elesbão Veloso' },
  { id: 61, nome: 'Eliseu Martins' },
  { id: 62, nome: 'Esperantina' },
  { id: 63, nome: 'Fartura do Piauí' },
  { id: 64, nome: 'Flores do Piauí' },
  { id: 65, nome: 'Floresta do Piauí' },
  { id: 66, nome: 'Floriano' },
  { id: 67, nome: 'Francinópolis' },
  { id: 68, nome: 'Francisco Ayres' },
  { id: 69, nome: 'Francisco Macedo' },
  { id: 70, nome: 'Francisco Santos' },
  { id: 71, nome: 'Fronteiras' },
  { id: 72, nome: 'Geminiano' },
  { id: 73, nome: 'Gilbués' },
  { id: 74, nome: 'Guadalupe' },
  { id: 75, nome: 'Guaribas' },
  { id: 76, nome: 'Hugo Napoleão' },
  { id: 77, nome: 'Ilha Grande' },
  { id: 78, nome: 'Inhuma' },
  { id: 79, nome: 'Ipiranga do Piauí' },
  { id: 80, nome: 'Isaías Coelho' },
  { id: 81, nome: 'Itainópolis' },
  { id: 82, nome: 'Itaueira' },
  { id: 83, nome: 'Jacobina do Piauí' },
  { id: 84, nome: 'Jaicós' },
  { id: 85, nome: 'Jardim do Mulato' },
  { id: 86, nome: 'Jatobá do Piauí' },
  { id: 87, nome: 'Jerumenha' },
  { id: 88, nome: 'João Costa' },
  { id: 89, nome: 'Joaquim Pires' },
  { id: 90, nome: 'Joca Marques' },
  { id: 91, nome: 'José de Freitas' },
  { id: 92, nome: 'Juazeiro do Piauí' },
  { id: 93, nome: 'Júlio Borges' },
  { id: 94, nome: 'Jurema' },
  { id: 95, nome: 'Lagoinha do Piauí' },
  { id: 96, nome: 'Lagoa Alegre' },
  { id: 97, nome: 'Lagoa do Barro do Piauí' },
  { id: 98, nome: 'Lagoa de São Francisco' },
  { id: 99, nome: 'Lagoa do Piauí' },
  { id: 100, nome: 'Lagoa do Sítio' },
  { id: 101, nome: 'Landri Sales' },
  { id: 102, nome: 'Luís Correia' },
  { id: 103, nome: 'Luzilândia' },
  { id: 104, nome: 'Madeiro' },
  { id: 105, nome: 'Manoel Emídio' },
  { id: 106, nome: 'Marcolândia' },
  { id: 107, nome: 'Marcos Parente' },
  { id: 108, nome: 'Massapê do Piauí' },
  { id: 109, nome: 'Matias Olímpio' },
  { id: 110, nome: 'Miguel Alves' },
  { id: 111, nome: 'Miguel Leão' },
  { id: 112, nome: 'Milton Brandão' },
  { id: 113, nome: 'Monsenhor Gil' },
  { id: 114, nome: 'Monsenhor Hipólito' },
  { id: 115, nome: 'Monte Alegre do Piauí' },
  { id: 116, nome: 'Morro Cabeça no Tempo' },
  { id: 117, nome: 'Morro do Chapéu do Piauí' },
  { id: 118, nome: 'Murici dos Portelas' },
  { id: 119, nome: 'Nazaré do Piauí' },
  { id: 120, nome: 'Nazária' },
  { id: 121, nome: 'Nossa Senhora de Nazaré' },
  { id: 122, nome: 'Nossa Senhora dos Remédios' },
  { id: 123, nome: 'Nova Santa Rita' },
  { id: 124, nome: 'Novo Oriente do Piauí' },
  { id: 125, nome: 'Novo Santo Antônio' },
  { id: 126, nome: 'Oeiras' },
  { id: 127, nome: 'Olho dÁgua do Piauí' },
  { id: 128, nome: 'Padre Marcos' },
  { id: 129, nome: 'Paes Landim' },
  { id: 130, nome: 'Pajeú do Piauí' },
  { id: 131, nome: 'Palmeira do Piauí' },
  { id: 132, nome: 'Palmeirais' },
  { id: 133, nome: 'Paquetá' },
  { id: 134, nome: 'Parnaguá' },
  { id: 135, nome: 'Parnaíba' },
  { id: 136, nome: 'Passagem Franca do Piauí' },
  { id: 137, nome: 'Patos do Piauí' },
  { id: 138, nome: 'Pau DArco do Piauí' },
  { id: 139, nome: 'Paulistana' },
  { id: 140, nome: 'Pavussu' },
  { id: 141, nome: 'Pedro II' },
  { id: 142, nome: 'Pedro Laurentino' },
  { id: 143, nome: 'Picos' },
  { id: 144, nome: 'Pimenteiras' },
  { id: 145, nome: 'Pio IX' },
  { id: 146, nome: 'Piracuruca' },
  { id: 147, nome: 'Piripiri' },
  { id: 148, nome: 'Porto' },
  { id: 149, nome: 'Porto Alegre do Piauí' },
  { id: 150, nome: 'Prata do Piauí' },
  { id: 151, nome: 'Queimada Nova' },
  { id: 152, nome: 'Redenção do Gurguéia' },
  { id: 153, nome: 'Regeneração' },
  { id: 154, nome: 'Riacho Frio' },
  { id: 155, nome: 'Ribeira do Piauí' },
  { id: 156, nome: 'Ribeiro Gonçalves' },
  { id: 157, nome: 'Rio Grande do Piauí' },
  { id: 158, nome: 'Santa Cruz do Piauí' },
  { id: 159, nome: 'Santa Cruz dos Milagres' },
  { id: 160, nome: 'Santa Filomena' },
  { id: 161, nome: 'Santa Luz' },
  { id: 162, nome: 'Santa Rosa do Piauí' },
  { id: 163, nome: 'Santana do Piauí' },
  { id: 164, nome: 'Santo Antônio de Lisboa' },
  { id: 165, nome: 'Santo Antônio dos Milagres' },
  { id: 166, nome: 'Santo Inácio do Piauí' },
  { id: 167, nome: 'São Braz do Piauí' },
  { id: 168, nome: 'São Félix do Piauí' },
  { id: 169, nome: 'São Francisco de Assis do Piauí' },
  { id: 170, nome: 'São Francisco do Piauí' },
  { id: 171, nome: 'São Gonçalo do Gurguéia' },
  { id: 172, nome: 'São Gonçalo do Piauí' },
  { id: 173, nome: 'São João da Canabrava' },
  { id: 174, nome: 'São João da Fronteira' },
  { id: 175, nome: 'São João da Serra' },
  { id: 176, nome: 'São João da Varjota' },
  { id: 177, nome: 'São João do Arraial' },
  { id: 178, nome: 'São João do Piauí' },
  { id: 179, nome: 'São José do Divino' },
  { id: 180, nome: 'São José do Peixe' },
  { id: 181, nome: 'São José do Piauí' },
  { id: 182, nome: 'São Julião' },
  { id: 183, nome: 'São Lourenço do Piauí' },
  { id: 184, nome: 'São Luis do Piauí' },
  { id: 185, nome: 'São Miguel da Baixa Grande' },
  { id: 186, nome: 'São Miguel do Fidalgo' },
  { id: 187, nome: 'São Miguel do Tapuio' },
  { id: 188, nome: 'São Pedro do Piauí' },
  { id: 189, nome: 'São Raimundo Nonato' },
  { id: 190, nome: 'Sebastião Barros' },
  { id: 191, nome: 'Sebastião Leal' },
  { id: 192, nome: 'Sigefredo Pacheco' },
  { id: 193, nome: 'Simões' },
  { id: 194, nome: 'Simplício Mendes' },
  { id: 195, nome: 'Socorro do Piauí' },
  { id: 196, nome: 'Sussuapara' },
  { id: 197, nome: 'Tamboril do Piauí' },
  { id: 198, nome: 'Tanque do Piauí' },
  { id: 199, nome: 'Teresina' },
  { id: 200, nome: 'União' },
  { id: 201, nome: 'Uruçuí' },
  { id: 202, nome: 'Valença do Piauí' },
  { id: 203, nome: 'Várzea Branca' },
  { id: 204, nome: 'Várzea Grande' },
  { id: 205, nome: 'Vera Mendes' },
  { id: 206, nome: 'Vila Nova do Piauí' },
  { id: 207, nome: 'Wall Ferraz' }
];

export const getCidadesPI = () => cidadesPI;
export const getCidadeById = (id) => cidadesPI.find(cidade => cidade.id === id);
export const getCidadeByNome = (nome) => cidadesPI.find(cidade => cidade.nome === nome);

// Coordenadas oficiais aproximadas (fallback) para cidades-chave do Piauí
// Fonte: Open data / OSM aproximado para centro urbano
export const cidadeCoordsPI = {
  'Teresina': { lat: -5.091944, lng: -42.803364 },
  'José de Freitas': { lat: -4.751528, lng: -42.574707 },
  'Campo Maior': { lat: -4.821034, lng: -42.167412 },
  'Parnaíba': { lat: -2.905705, lng: -41.775364 },
  'Piracuruca': { lat: -3.933273, lng: -41.708069 }
};

export const getCoordsByNome = (nome) => {
  if (!nome) return null;
  const key = String(nome).trim();
  if (cidadeCoordsPI[key]) return cidadeCoordsPI[key];
  // tentativa sem acentos/caso
  const deaccent = (s) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const norm = deaccent(key).toLowerCase();
  for (const k of Object.keys(cidadeCoordsPI)) {
    if (deaccent(k).toLowerCase() === norm) return cidadeCoordsPI[k];
  }
  return null;
};
