export const cidadesPI = [
  { id: 1, nome: 'Teresina' },
  { id: 2, nome: 'Picos' },
  { id: 3, nome: 'Campo Maior' },
  { id: 4, nome: 'Parnaíba' },
  { id: 5, nome: 'Caxias' },
  { id: 6, nome: 'Timon' },
  { id: 7, nome: 'Floriano' },
  { id: 8, nome: 'São Raimundo Nonato' },
  { id: 9, nome: 'José de Freitas' },
  { id: 10, nome: 'Uruçuí' },
  { id: 11, nome: 'Oeiras' },
  { id: 12, nome: 'Piripiri' },
  { id: 13, nome: 'Amarante' },
  { id: 14, nome: 'Barras' },
  { id: 15, nome: 'Paranaguá' },
  { id: 16, nome: 'Altos' },
  { id: 17, nome: 'Santa Luzia do Piauí' },
  { id: 18, nome: 'São João do Piauí' },
  { id: 19, nome: 'São Miguel do Tapuio' },
  { id: 20, nome: 'São Pedro do Piauí' },
  { id: 21, nome: 'São Lourenço do Piauí' },
  { id: 22, nome: 'São Francisco do Piauí' },
  { id: 23, nome: 'São José do Piauí' },
  { id: 24, nome: 'São Gonçalo do Piauí' },
  { id: 25, nome: 'São João da Canabrava' },
  { id: 26, nome: 'São João da Serra' },
  { id: 27, nome: 'São João da Fronteira' },
  { id: 28, nome: 'São João do Arraial' },
  { id: 29, nome: 'São Gonçalo do Gurguéia' },
  { id: 30, nome: 'São João da Varjota' },
  { id: 31, nome: 'São Pedro do Piauí' },
  { id: 32, nome: 'São Raimundo Nonato' },
  { id: 33, nome: 'São Sebastião do Piauí' },
  { id: 34, nome: 'São Tiago do Piauí' },
  { id: 35, nome: 'São Valério do Piauí' },
  { id: 36, nome: 'São Vicente do Piauí' },
  { id: 37, nome: 'São Miguel do Tapuio' },
  { id: 38, nome: 'São Pedro do Piauí' },
  { id: 39, nome: 'São Raimundo Nonato' },
  { id: 40, nome: 'São Sebastião do Piauí' },
  { id: 41, nome: 'São Tiago do Piauí' },
  { id: 42, nome: 'São Valério do Piauí' },
  { id: 43, nome: 'São Vicente do Piauí' },
  { id: 44, nome: 'São Miguel do Tapuio' },
  { id: 45, nome: 'São Pedro do Piauí' },
  { id: 46, nome: 'São Raimundo Nonato' },
  { id: 47, nome: 'São Sebastião do Piauí' },
  { id: 48, nome: 'São Tiago do Piauí' },
  { id: 49, nome: 'São Valério do Piauí' },
  { id: 50, nome: 'São Vicente do Piauí' }
];

export const getCidadesPI = () => cidadesPI;
export const getCidadeById = (id) => cidadesPI.find(cidade => cidade.id === id);
export const getCidadeByNome = (nome) => cidadesPI.find(cidade => cidade.nome === nome);
